FROM nginx:1.19-alpine

COPY prod_templates /etc/nginx/templates
COPY errors /var/www/default
RUN mkdir /etc/letsencrypt


RUN apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev rust cargo
RUN pip3 install pip --upgrade
RUN pip3 install certbot-nginx